# TODO: initial setup

name: Create PR and Notify
description: Create PR from sourceBranch to featureBranch

inputs:
  serverAddress:
    description: 'the email server's address'
    type: string
    required: true
    default: 'smtp.gmail.com'
  serverPort:
    description: 'the port number used to login to your email server'
    type: int
    required: true
    default: 465
  emailAddress:
      description: 'the email address used to login to your email server'
      type: string
      required: true
  emailPassword:
    description: 'password used to login to your email server'
    type: string
    required: true      
  toEmailAddress:
    description: 'the email address a notification email will be sent to'
    type: string
    required: true

runs:
  using: "composite"
  steps:        
    # TODO: start PR from ${{ (github.event.inputs || inputs).featureBranch }} to ${{ (github.event.inputs || inputs).featureBranch }} if any conflicts
    - id: startPRAndNotification

    # send an email notifying of the failure
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: ${{ (github.event.inputs || inputs).serverAddress }}
        # Required mail server port:
        server_port: ${{ (github.event.inputs || inputs).serverPort }}
        # Optional (recommended): mail server username:
        username: ${{ (github.event.inputs || inputs).emailAddress }}
        # Optional (recommended) mail server password:
        password: ${{ (github.event.inputs || inputs).emailPassword }}
        # Required mail subject:
        subject: PR Created ${{ (github.event.inputs || inputs).sourceBranch }} -> ${{ (github.event.inputs || inputs).featureBranch }} auto-merge failed with conflicts!
        # Required recipients' addresses:
        to: ${{ (github.event.inputs || inputs).toEmailAddress }}
        # Required sender full name (address can be skipped):
        from: ${{ (github.event.inputs || inputs).gitHubUsername }}
        # TODO: get actual key from PR action
        body: | 
          <p>
             Merge failed when attempting to merge ${{ (github.event.inputs || inputs).sourceBranch }} into ${{ (github.event.inputs || inputs).featureBranch }}.
             PR Created, <<a href="PR URL FROM PR STEP HERE">view on GitHub</a>
          </p>
