branding:
  icon: 'mail'
  color: 'purple'

name: Auto-Merge PR Notification
description: Send notification that PR was created from sourceBranch to featureBranch
inputs:
  serverAddress:
    description: "the email server's address"
    type: string
    required: true
    default: 'smtp.gmail.com'
  serverPort:
    description: 'the port number used to login to your email server'
    type: string
    required: true
    default: '465'
  emailAddress:
    description: 'the email address used to login to your email server'
    type: string
    required: true
  emailPassword:
    description: 'password used to login to your email server'
    type: string
    required: true      
  toEmailAddress:
    description: 'the email address a notification email will be sent to'
    type: string
    required: true
  featureBranch:
    description: 'featureBranch: the branch being updated with sourceBranch'
    type: string
    required: true
  sourceBranch:
    description: 'sourceBranch: the branch being merged into featureBranch'
    type: string
    required: true
    default: 'develop'
  name:
    description: 'the name the email is from'
    type: string
    required: true
    default: 'Auto Merge Triage'
  prURL:
    description: "the PR's URL"
    type: string
    required: true
    default: 'https://github.com/NLSInc/Einstein-iOS/pulls'    

runs:
  using: "composite"
  steps:  
    - id: debug
      shell: bash
      run: echo ${{ (github.event.inputs || inputs) }}
      
    - id: email_notification
    # send an email notifying of the failure
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: ${{ (github.event.inputs || inputs).serverAddress }}
        # Required mail server port:
        server_port: ${{ (github.event.inputs || inputs).serverPort }}
        # Optional (recommended): mail server username:
        username: ${{ (github.event.inputs || inputs).emailAddress }}
        # Optional (recommended) mail server password:
        password: ${{ (github.event.inputs || inputs).emailPassword }}
        # Required mail subject:
        subject: PR Created ${{ (github.event.inputs || inputs).sourceBranch }} -> ${{ (github.event.inputs || inputs).featureBranch }} auto-merge failed with conflicts!
        # Required recipients' addresses:
        to: ${{ (github.event.inputs || inputs).toEmailAddress }}
        # Required sender full name (address can be skipped):
        from: ${{ (github.event.inputs || inputs).name }}
        body: | 
          <p>
             Merge failed when attempting to merge ${{ (github.event.inputs || inputs).sourceBranch }} into ${{ (github.event.inputs || inputs).featureBranch }}.
             <a href="${{ (github.event.inputs || inputs).prURL }}">View PR on GitHub</a>
             <a href="${{ (github.event.inputs || inputs).prURL }}/conflicts">Any conflicts appear here</a>
          </p>
